

POST http://0.0.0.0:8080/api/auth/register
Content-Type: application/json

{
  "email": "a2@mail.ru",
  "password": "123456"
}


POST http://0.0.0.0:8080/api/auth/login
Content-Type: application/json

{
  "email": "a2@mail.ru",
  "password": "123456"
}


POST http://0.0.0.0:8080/api/posts/addPost
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MWEzM2U1NTg0ZTI4MmViYjNmOTI3M2UiLCJpYXQiOjE2MzgxMjQwMjksImV4cCI6MTYzODE0MjAyOX0.m0sfxsejzzq9vSH2Mg-e0EpHki2u5ck9fW8DpGthNaY

{
  "title": "4Title example",
  "content": "Hellororld eqr qer eqr eqr 13r3 1r31 r3"
}

GET http://0.0.0.0:8080/api/posts/posts?offset=1&length=2
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MWEzM2U1NTg0ZTI4MmViYjNmOTI3M2UiLCJpYXQiOjE2MzgxMjQwMjksImV4cCI6MTYzODE0MjAyOX0.m0sfxsejzzq9vSH2Mg-e0EpHki2u5ck9fW8DpGthNaY



GET http://localhost:8080/
